name: flutter_application_1
description: "A new Flutter project."
# 以下行防止该包被意外发布到 pub.dev。
# 这对于私有包是首选的。
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 以下定义了应用程序的版本和构建号。
# 版本号由三个用点分隔的数字组成，例如 1.2.43
# 后面可以跟一个用 + 分隔的可选构建号。
# 在 flutter build 中可以通过指定 --build-name 和 --build-number 覆盖版本和构建号。
# 在 Android 中，build-name 用作 versionName，而 build-number 用作 versionCode。
# 在此处阅读更多关于 Android 版本的信息：https://developer.android.com/studio/publish/versioning
# 在 iOS 中，build-name 用作 CFBundleShortVersionString，而 build-number 用作 CFBundleVersion。
# 在此处阅读更多关于 iOS 版本的信息：
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 在 Windows 中，build-name 用作产品和文件版本的主要、次要和修订部分，而 build-number 用作构建后缀。
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# 依赖项指定了您的包需要的其他包才能正常工作。
# 要自动升级包依赖到最新版本，
# 可以考虑运行 `flutter pub upgrade --major-versions`。
# 或者，可以通过将下面的版本号手动更新为 pub.dev 上可用的最新版本来手动更新依赖项。
# 要查看哪些依赖项有更新的版本可用，请运行 `flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3
  fluro: ^2.0.5

  # 以下将 Cupertino Icons 字体添加到您的应用程序中。
  # 与 CupertinoIcons 类一起使用以获得 iOS 样式的图标。
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 下面的 "flutter_lints" 包包含了一组推荐的 lint 规则，
  # 以鼓励良好的编码实践。该包提供的 lint 集在
  # 包根目录下的 `analysis_options.yaml` 文件中激活。
  # 有关停用特定 lint 规则和激活其他规则的信息，请参见该文件。
  flutter_lints: ^3.0.0

# 有关该文件的通用 Dart 部分的信息，请参见
# 以下页面：https://dart.dev/tools/pub/pubspec

# 以下部分是特定于 Flutter 包的。
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - images/welfareBg.png
  # 要向应用程序添加资源，请添加一个资源部分，如下所示：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 图像资产可以引用一个或多个特定分辨率的“变体”，请参见
  # https://flutter.dev/assets-and-images/#resolution-aware

  # 有关从包依赖项添加资产的详细信息，请参见
  # https://flutter.dev/assets-and-images/#from-packages

  # 要向应用程序添加自定义字体，请在此处添加一个字体部分，
  # 在这个“flutter”部分中。该列表中的每个条目都应该有一个
  # “family”键，其中包含字体家族名称，以及一个“fonts”键，
  # 其中包含资产和字体的其他描述符。例如：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关来自包依赖项的字体的详细信息，
  # 请参见：https://flutter.dev/custom-fonts/#from-packages
